### ISSUE TITLE
Reorganise crates

### ISSUE THREAD

**Issue by kontheocharis** [hash-org/lang#29]
The code structure is currently:

- [x] hash-ast
  - Contains the AST definitions, used in various places
  - Also contains the IntoAst trait which any parser will have to implement.

- [x] hash-pest-parser
  - The pest parser, uses hash-ast

- [x] hash-ir
  - Contains the definitions for the hash IR

- [x] hash-transform
  - What is now hash-typecheck, uses hash-ast and hash-ir, to convert AST into IR

- [x] hash-backend-vm
  - VM backend, receives IR and transforms it into an instruction set, and runs it

- [x] hash
  - The main crate, exposing the CLI and REPL

- [x] hash-reporting
   - Deals with errors and other kinds of reporting to the console. Contains various tools for formatting errors, code snippets, labelling various parts of the code, rust borrow checker-style.

Additionally, we will move all the crates into a folder called 'compiler' to separate it from the library, examples, and docs folders that are not related to the compiler sources.

**Comment by feds01** [comment]
@kontheocharis Surely, `hash-transform` should be separate from `hash-typecheck` ?
