### ISSUE TITLE
Naming: Use consistent naming between typechecker and parser

### ISSUE THREAD

**Issue by kontheocharis** [hash-org/lang#346]
Currently the parser naming of AST elements differs from the typechecker's. For example, `TyFnTy` vs `TypeFunction`, and `TyFn` vs `TypeFunctionDef`, `TypeFunctionCall` vs `AppTyFn`. These should probably be brought closer together for consistency's sake.

**Comment by feds01** [comment]
What should the naming conventions be? I feel like both names have merit...

**Comment by kontheocharis** [comment]
`TyFnCall`, `TyFnTy`, `TyFnDef`?
