### ISSUE TITLE
TC: Properly ensure impls implement their traits, and infer original types while at it

### ISSUE THREAD

**Issue by kontheocharis** [hash-org/lang#389]
1. Ensure all members in the impl appear in the trait, and have correct types (extension: if types are incomplete, infer from trait. Maybe this should be done in the future). (Unification needs to happen with src=impl and target=trait)
3. Ensure all members in the trait appear in the impl.

**Comment by feds01** [comment]
Is `1` not already implemented here:
https://github.com/hash-org/lang/blob/b8b30751a648016b10e71bda13163be4ec099a9a/compiler/hash-typecheck/src/ops/validate.rs#L235-L241

?

**Comment by kontheocharis** [comment]
Yes, I was just writing everything for completeness.

**Comment by feds01** [comment]
So everything is complete here? Ill be putting a PR that polishes error reporting a bit and then this will close it?

**Comment by kontheocharis** [comment]
> So everything is complete here? Ill be putting a PR that polishes error reporting a bit and then this will close it?

Actually yes, it seems so.
