### ISSUE TITLE
Add integer range patterns

### ISSUE THREAD

**Issue by feds01** [hash-org/lang#438]
In an effort to consolidate the typechecking `primitives::Pat` and `exhaustiveness::lower::Pat`  data structures, integer ranges need to be added to the language:

Questions to answer:

- What is the syntax? My proposition would be:
-  - `a..b` for open range, as in ` a <= x < b`
-  - `a..=b` for open range, as in ` a <= x <= b`
-  - `a..` for unbounded range, as in ` a <= x <= type_of(a)::MAX` with the assumption that `a` is of an integral type
-  - should we have some kind of stepping variant?

Things that need to be done:
- AST:
-  - New `pat` variant
- Support in parsing
- Semantic Analysis (ensure range makes sense)
-  - lower bound is smaller or equal to the upper bound 
-  Support in tc traversal
- Support in exhaustiveness checking (needs to be hooked up with existing logic)

@kontheocharis thoughts?

**Comment by kontheocharis** [comment]
What about `a..<b` for exclusive end and `a..b` for inclusive end?

**Comment by kontheocharis** [comment]
`a..+1..b`, `a..-1..b` for steps? Although this is only for iterators, which is a different discussion

**Comment by kontheocharis** [comment]
```
for i in 1..+2..end { whatever(i)
```

**Comment by kontheocharis** [comment]
```rs
end := get_endpoint();

match i {
    1..end => ..,
    _ => ..
}
```
