### ISSUE TITLE
Tokeniser: Float parsing is greedy and doesn't consider infix calls:

### ISSUE THREAD

**Issue by feds01** [hash-org/lang#57]
## Problem
The following expression is currently incorrectly tokenised:

```
2.pow(3)
```

Generated tokens:
```
>>> 2.pow(3)
FloatLiteral(2.0)
Ident (pow)
Delimiter(()
IntLiteral(3)
Delimiter())
```

Parsed as:
```
>>> :d 2.pow(3)
└─float 2
```

Since the float parser is greedy, it will consider that the `2.` is the final end of a literal. However, in this situation, this is an infix call to the function `pow` with the arguments `2` and `3`.

Ideally, the parser should take in context and prevent the float tokeniser from eating in the incorrect context.

## Possible solution
The problem can be fixed by either:
- Prevent the tokeniser from creating a float literal if an `ident` friendly char is right after the `dot`.
- Disallow float literals with no digits after the decimal point.

@kontheocharis What do you think?

**Comment by kontheocharis** [comment]
Second point sounds reasonable to me, though both seem like good solutions. We might want to implement both?
