### ISSUE TITLE
Improve lexing by storing all tokens in a flat fashion

### ISSUE THREAD

**Issue by kontheocharis** [hash-org/lang#84]
Currently, in hash-parser, the parser stores trees of tokens (by nested braces/parens) as separate vectors. This is wasteful in terms of allocation. It would be better if they were all stored in the same vector, and each opening brace token had a position offset stored within it to the closing brace. This way, the parsing can still be parallelised while not having to resort to multiple vectors.

**Comment by feds01** [comment]
Am I correct in assuming that the initial changes are on the `ast-tests` branch?

**Comment by feds01** [comment]
After some investigation, it's noted that full flattening yields no performance gain to rather using partial token trees. Therefore, keeping with the same token tree API is more ergonomic in the codebase and therefore further efforts on flattening won't be carried out.

**Comment by feds01** [comment]
This issue was resolved by https://github.com/hash-org/lang/pull/93
